name: deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install locale
        run: |
          sudo locale-gen pt_PT.UTF-8
          sudo update-locale LANG=pt_PT.UTF-8

      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Cache vendored data
        uses: actions/cache@v2
        with:
          path: vendor
          key: vendor-data

      - name: Download COVID19 data
        run: ./update-data.sh
        continue-on-error: ${{ github.event_name != 'schedule' }}
          
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            .venv

          key: pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install and Build
        run: |
          pip install poetry
          poetry config virtualenvs.in-project true
          poetry install

      - name: Generate charts
        run: poetry run python chart.py

      - name: Generate csv
        run: poetry run python heatmap.py

      - name: Move outputs
        run: mv output public/output
          
      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: http
          folder: public
          clean: true
